USE PROJECT ;

SELECT * FROM MAINDATA_FINAL;
 
SELECT DATE(CONCAT_WS('-', year, month, day)) AS DATE FROM MAINDATA_FINAL;

 
ALTER TABLE MAINDATA_FINAL 
DROP COLUMN DATE ;
 
ALTER TABLE MAINDATA_FINAL 
ADD COLUMN DATE_FIELD DATE;
   
UPDATE MAINDATA_FINAL
SET DATE_FIELD=DATE(CONCAT_WS('-', year, month, day));
   
ALTER TABLE MAINDATA_FINAL 
ADD COLUMN YEAR_FIELD VARCHAR(50);
   
UPDATE MAINDATA_FINAL
SET YEAR_FIELD=YEAR(DATE_FIELD);
   
ALTER TABLE MAINDATA_FINAL 
ADD COLUMN MONTH_NO VARCHAR(50);

UPDATE MAINDATA_FINAL
SET MONTH_NO=MONTH(DATE_FIELD);

ALTER TABLE MAINDATA_FINAL 
ADD COLUMN MONTH_FULLNAME VARCHAR(50);

UPDATE MAINDATA_FINAL
SET MONTH_FULLNAME=MONTHNAME(DATE_FIELD);

ALTER TABLE MAINDATA_FINAL 
ADD COLUMN QUARTER VARCHAR(50);

UPDATE MAINDATA_FINAL
SET QUARTER=CONCAT("Q",QUARTER(DATE_FIELD));

ALTER TABLE MAINDATA_FINAL 
ADD COLUMN YEARMONTH VARCHAR(50);

UPDATE MAINDATA_FINAL
SET YEARMONTH=CONCAT(YEAR(DATE_FIELD),"-",MONTHNAME(DATE_FIELD));

SELECT WEEKDAY(DATE_FIELD) FROM MAINDATA_FINAL;

ALTER TABLE MAINDATA_FINAL 
ADD COLUMN WEEKDAY_NO VARCHAR(50);

UPDATE MAINDATA_FINAL
SET WEEKDAY_NO=WEEKDAY(DATE_FIELD);


ALTER TABLE MAINDATA_FINAL 
ADD COLUMN WEEKDAY_NAME VARCHAR(50);

UPDATE MAINDATA_FINAL
SET WEEKDAY_NAME=DAYNAME(DATE_FIELD);

ALTER TABLE MAINDATA_FINAL 
ADD COLUMN FINANCIAL_MONTH VARCHAR(50);

UPDATE MAINDATA_FINAL
SET FINANCIAL_MONTH=(
CASE MONTH_FULLNAME WHEN "APRIL" THEN 1 
                    WHEN "MAY" THEN 2
                    WHEN "JUNE" THEN 3
                    WHEN "JULY" THEN 4
                    WHEN "AUGUST" THEN 5
                    WHEN "SEPTEMBER" THEN 6
                    WHEN "OCTOBER" THEN 7
                    WHEN "NOVEMBER" THEN 8
                    WHEN "DECEMBER" THEN 9
					WHEN "JANUARY" THEN 10
                    WHEN "FEBRUARY" THEN 11
                    WHEN "MARCH" THEN 12
                    
                    END);


ALTER TABLE MAINDATA_FINAL 
ADD COLUMN FINANCIAL_QUARTER VARCHAR(50);

UPDATE MAINDATA_FINAL
SET FINANCIAL_QUARTER=4
WHERE MONTH_NO IN (1,2,3);

UPDATE MAINDATA_FINAL
SET FINANCIAL_QUARTER=1
WHERE MONTH_NO IN (4,5,6);

UPDATE MAINDATA_FINAL
SET FINANCIAL_QUARTER=2
WHERE MONTH_NO IN (7,8,9);

UPDATE MAINDATA_FINAL
SET FINANCIAL_QUARTER=3
WHERE MONTH_NO IN (10,11,12);


--- 2. Find the load Factor percentage on a yearly , Quarterly , Monthly basis ( Transported passengers / Available seats)

ALTER TABLE MAINDATA_FINAL
ADD COLUMN LOAD_FACTOR DECIMAL;

UPDATE MAINDATA_FINAL
SET LOAD_FACTOR=((TRANSPORTED_PASSENGERS/AVAILABLE_SEATS)*100) ;

SELECT YEAR,AVG(LOAD_FACTOR) FROM MAINDATA_FINAL
GROUP BY YEAR_FIELD;

--- 3. Find the load Factor percentage on a Carrier Name basis ( Transported passengers / Available seats)

SELECT * FROM MAINDATA_FINAL;

SELECT CARRIER_NAME ,AVG(LOAD_FACTOR) FROM MAINDATA_FINAL
GROUP BY CARRIER_NAME;


---- 4. Identify Top 10 Carrier Names based passengers preference 

SELECT CARRIER_NAME,SUM(TRANSPORTED_PASSENGERS) FROM MAINDATA_FINAL
GROUP BY CARRIER_NAME
ORDER BY SUM(TRANSPORTED_PASSENGERS) DESC limit 10;

--- 5. Display top Routes ( from-to City) based on Number of Flights 

SELECT (FROMTO_CITY),COUNT((AIRLINE_ID)) FROM MAINDATA_FINAL
GROUP BY AIRLINE_ID 
ORDER BY COUNT((AIRLINE_ID)) DESC LIMIT 10;

--- 6. Identify the how much load factor is occupied on Weekend vs Weekdays.

SELECT* FROM MAINDATA_FINAL;

ALTER TABLE MAINDATA_FINAL 
ADD COLUMN WEEKDAY_WEEKEND VARCHAR(50);
 
 
UPDATE MAINDATA_FINAL
SET WEEKDAY_WEEKEND='WEEKDAY'
WHERE WEEKDAY_NO IN (0,1,2,3,4); 

UPDATE MAINDATA_FINAL
SET WEEKDAY_WEEKEND='WEEKEND'
WHERE WEEKDAY_NO IN (5,6); 

SELECT WEEKDAY_WEEKEND,AVG(LOAD_FACTOR) FROM MAINDATA_FINAL
GROUP BY WEEKDAY_WEEKEND;


--- 8. Identify number of flights based on Distance groups

SELECT * FROM DISTANCE_GROUPS;

SELECT * FROM MAINDATA_FINAL;

SELECT D.DISTANCE_INTERVAL,COUNT(AIRLINE_ID)
FROM DISTANCE_GROUPS  D
JOIN
MAINDATA_FINAL  M
USING(DISTANCEGROUP_ID)
GROUP BY DISTANCE_INTERVAL
ORDER BY COUNT(AIRLINE_ID) DESC;